apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Chart.Name }}-config-templates
  labels:
    app: {{ $.Chart.Name }} 
    component: {{ $.Chart.Name }}-config-templates
data:
  {{ $.Chart.Name }}-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otelcol'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']
            metric_relabel_configs:
            - source_labels: [ __name__ ]
              regex: '.*grpc_io.*'
              action: drop
      k8s_cluster:
        collection_interval: 10s
      hostmetrics:
        scrapers:
          cpu:
            metrics:
                system.cpu.utilization:
                  enabled: true
          disk:
          filesystem:
          load:
          memory:
          network:
          processes:
      otlp:
        protocols:
          grpc:
            endpoint: ":5317"
          http:
            endpoint: ":5318"
    exporters:
      otlp:
        endpoint: "${HOST_IP}:4317"
        tls: 
          insecure: true
      datadog:
        api:
          key: '{% with secret "kv/k8s/otel/shared/dd_otel" %}{% .Data.data.api_key %}{% end %}'
          site: datadoghq.com
    processors:
      resourcedetection:
        # ensures host.name and other important resource tags 
        # get picked up
        detectors: [system, env]
        timeout: 5s
        override: false
      # adds various tags related to k8s
      k8sattributes:
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s
    service:
      pipelines:
        metrics:
          receivers: [otlp,k8s_cluster,hostmetrics, prometheus]
          processors: [batch,k8sattributes, resourcedetection]
          exporters: [datadog,otlp]

        traces:
          receivers: [otlp]
          processors: [resourcedetection, k8sattributes, batch]
          exporters: [datadog,otlp]
