apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-agent
  labels:
    app: opentelemetry
    component: otel-collector
spec:

  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      tolerations:
        - key: node
          operator: Equal
          value: otel-small
          effect: NoSchedule        
      serviceAccountName: otel-collector-account
      containers:
      - name: collector
        command:
          - "/otelcol-contrib"
          - "--config=/conf/otel-agent-config.yaml"
        image: otel/opentelemetry-collector-contrib:0.54.0
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "k8s.pod.ip=$(POD_IP)"
        ports:
        - containerPort: 4318 # default port for OpenTelemetry HTTP receiver.
          hostPort: 4318
        - containerPort: 4317 # default port for OpenTelemetry gRPC receiver.
          hostPort: 4317
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: otel-agent-config-vol
          mountPath: /conf
      initContainers:
      - name: consul-template-init
        image: 727006795293.dkr.ecr.us-east-1.amazonaws.com/consul-template:v7424220-83a8930-0.27.2-dd.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/datadog
        - name: templates
          mountPath: /etc/templates
        args:
        - -once
        - -template=/etc/templates/otel-agent-config.yaml:/conf/otel-agent-config.yaml
        env:
        - name: DD_DATACENTER
          value: us1.staging.dog
        - name: DD_SITE
          value: datad0g.com
      volumes:
      - name: templates
        configMap:
          name: {{ $.Chart.Name }}-templates
      - name: config
        emptyDir: {} 
      volumes:
      - name: otlpgen
        hostPath:
          path: /otlpgen
      - name: otel-agent-config-vol
        configMap:
          name: otel-agent-conf
          items:
            - key: otel-agent-config
              path: otel-agent-config.yaml
