apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $.Chart.Name }}
  labels:
    app: {{ $.Chart.Name }}
spec:

  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        app: {{ $.Chart.Name }} 
        service: {{ $.Chart.Name }}
        team: {{ $.Values.team }}
    spec:
      hostNetwork: true
      tolerations:
        - key: node
          operator: Equal
          value: otel-small
          effect: NoSchedule        
      serviceAccountName: {{ $.Chart.Name }}
      containers:
      - name: collector
        command:
          - "/otelcol-contrib"
          - "--config=/etc/datadog/{{ $.Chart.Name }}-config.yaml"
          - "--config=/etc/processor/{{ $.Chart.Name }}-config-processor.yaml"
        image:  {{ $.Values.image.registry }}:{{ $.Values.image.tag }}
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "k8s.pod.ip=$(POD_IP)"
        ports:
        - containerPort: 5318 # default port for OpenTelemetry HTTP receiver.
          hostPort: 5318
        - containerPort: 5317 # default port for OpenTelemetry gRPC receiver.
          hostPort: 5317
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: config
          mountPath: /etc/datadog
        - name: {{ $.Chart.Name }}-config-processor
          mountPath: /etc/processor
      initContainers:
      - name: consul-template-init
        image:  "{{ $.Values.global.docker.registry }}/{{ $.Values.global.consulTemplate.image.name }}:{{ $.Values.global.consulTemplate.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        args:
        - -once
        - -template=/etc/templates/{{ $.Chart.Name }}-config.yaml:/etc/datadog/{{ $.Chart.Name }}-config.yaml
        env:
        - name: DD_DATACENTER
          value: us1.staging.dog
        - name: DD_SITE
          value: datad0g.com
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: {{ $.Chart.Name }}-config-templates
          mountPath: /etc/templates
        - name: config
          mountPath: /etc/datadog
      volumes:
        - name: otlpgen
          hostPath:
            path: /otlpgen
        - name: config
          emptyDir: {}
        - name: {{ $.Chart.Name }}-config-templates
          configMap:
            name: {{ $.Chart.Name }}-config-templates
        - name: {{ $.Chart.Name }}-config-templates
          configMap:
            name: {{ $.Chart.Name }}-config-templates
        - name: {{ $.Chart.Name }}-config-processor
          configMap:
            name: {{ $.Chart.Name }}-config-processor
