---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.Chart.Name }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $.Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ $.Chart.Name }}
  namespace: otel
roleRef:
  kind: ClusterRole
  name: {{ $.Chart.Name }}-role
  apiGroup: rbac.authorization.k8s.io
---
