
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
    component: otel-demo-cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
      component: otel-demo-cartservice
  template:
    metadata:
      labels:
        team: team-opentelemetry
        service: cartservice
        app: cartservice
        component: otel-demo-cartservice
    spec:
      
      tolerations:
      - key: node
        operator: Equal
        value: otel-small
        effect: NoSchedule
      containers:
      - name: cartservice
        image:  registry.ddbuild.io/otel-demo/cartservice:v0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 200m
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
               apiVersion: v1
               fieldPath: status.podIP
        - name: OTEL_RESOURCE
          value: k8s.pod.ip=$(MY_POD_IP)
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          # The application SDK must use this environment variable in order to succesfully
        - name: DD_DATACENTER
          value: us1.staging.dog
        - name: DD_SITE
          value: datad0g.com
        - name: OTEL_AGENT_ENDPOINT
          value: "$(HOST_IP)"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):5318"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):5317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=cartservice,deployment.environment=otel"
        - name: APP_ENV
          value: otel
        - name: CART_SERVICE_PORT
          value: "7070"
        - name: ASPNETCORE_URLS
          value: "http://*:$(CART_SERVICE_PORT)"
        - name: REDIS_ADDR
          value: "redis"

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
    component: otel-demo-cartservice
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 7070
      protocol: TCP
      name: http
  selector:
    app: cartservice
    component: otel-demo-cartservice
---

