
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    app: shippingservice
    component: otel-demo-shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
      component: otel-demo-shippingservice
  template:
    metadata:
      labels:
        team: team-opentelemetry
        service: shippingservice
        app: shippingservice
        component: otel-demo-shippingservice
    spec:
      
      tolerations:
      - key: node
        operator: Equal
        value: otel-small
        effect: NoSchedule
      containers:
      - name: shippingservice
        image:  registry.ddbuild.io/otel-demo/shippingservice:v0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 200m
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          # The application SDK must use this environment variable in order to succesfully
        - name: DD_DATACENTER
          value: us1.staging.dog
        - name: DD_SITE
          value: datad0g.com
        - name: OTEL_AGENT_ENDPOINT
          value: "otel-agent"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):4318"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=shippingservice"
        - name: APP_ENV
          value: staging
        - name: SHIPPING_SERVICE_PORT
          value: "50051"

---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app: shippingservice
    component: otel-demo-shippingservice
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      name: http
  selector:
    app: shippingservice
    component: otel-demo-shippingservice
---
