apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-demo-go-server-dd
  labels:
    app.kubernetes.io/component: go-server-dd
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-go-server-dd
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: "1.4.0"
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-demo-go-server-dd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: go-server-dd
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: opentelemetry-demo-go-server-dd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: alpha.eksctl.io/nodegroup-name
                    operator: In
                    values:
                      - ng-4
      containers:
        - name: go-server-dd
          image: 601427279990.dkr.ecr.us-east-1.amazonaws.com/otel-demo:PLACEHOLDER_COMMIT_SHA-go-server-dd
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8082
            name: ddgoserverport
            protocol: TCP
          env:
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: "metadata.labels['app.kubernetes.io/component']"
          - name: DD_ENV
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: DD_TRACE_AGENT_URL
            value: unix:///var/run/datadog/apm.socket
          volumeMounts:
          - name: apmsocketpath
            mountPath: /var/run/datadog
          resources:
            limits:
              memory: 1Gi
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000  
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath                              
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-demo-go-server-dd
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-demo-go-server-dd
  ports:
  - name: go-server-dd
    port: 8082
    protocol: TCP
    targetPort: 8082