agents:
  image:
    repository: 850406765696.dkr.ecr.us-west-2.amazonaws.com/08450328-agent
    tag: d9aa299375a0016e89eee50b9144b09e30d2d4d4-7-amd64
    doNotCheckTag: true
datadog:
  apiKey: $DD_API_KEY
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
