agents:
  image:
    tag: 7.52.0
datadog:
  apiKey: $DD_API_KEY
  apm:
    portEnabled: true
    port: 8126
  logs:
    enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
