agents:
  image:
    name: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent/agent
    tag: v30063998-2667a4b9-7-jmx-amd64
    doNotCheckTag: true
datadog:
  apiKey: $DD_API_KEY
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
