agents:
  image:
    tag: 7.50.0-rc.3
    tagSuffix: jmx
datadog:
  apiKey: $DD_API_KEY
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
