agents:
  image:
    tag: 7.51.0-rc.1
    tagSuffix: jmx
datadog:
  apiKey: $DD_API_KEY
  apm:
    portEnabled: true
    port: 8126
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
