agents:
  image:
    repository: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent/agent@sha256
    tag: 6a22f3cc9e525c47ba8ceaa26bcaa5a7215aad737d2a25fe5f088ff05e0757b1
    doNotCheckTag: true
datadog:
  apiKey: $DD_API_KEY
  logs:
    enabled: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
  env:
    - name: DD_API_KEY
      valueFrom:
        secretKeyRef:
          name: datadog-secrets
          key: api-key
          optional: false
