datadog:
  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true
  collectEvents: true
  apm:
    portEnabled: true
  logs:
    enabled: true
    containerCollectAll: true
  networkMonitoring:
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
        http:
          enabled: true
