apiVersion: batch/v1
kind: CronJob
metadata:
  name: runtime-metrics-tracker
spec:
  schedule: "0 9 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: runtime-metrics-tracker
              image: stanleyliu855/runtime-metrics-tracker:v1.0.3
              imagePullPolicy: IfNotPresent
              env:
                - name: SLACK_WEBHOOK_URL
                  value: SLACK_WEBHOOK_URL
          restartPolicy: OnFailure
