# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  datadog:
    api:
      key: DD_API_KEY
    host_metadata:
      tags:
        - otel:true

processors:
  resource:
    attributes:
      - key: deployment.environment   # Set env tag for Datadog
        value: "otel"
        action: upsert

service:
  pipelines:
    traces:
      processors: [ batch, resource]
      exporters: [otlp,  datadog, spanmetrics]
    metrics:
      processors: [batch, resource]
      exporters: [prometheus, logging, datadog]
