
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    component: otel-demo-paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
      component: otel-demo-paymentservice
  template:
    metadata:
      labels:
        team: team-opentelemetry
        service: paymentservice
        app: paymentservice
        component: otel-demo-paymentservice
    spec:
      
      tolerations:
      - key: node
        operator: Equal
        value: otel-small
        effect: NoSchedule
      containers:
      - name: paymentservice
        image:  registry.ddbuild.io/otel-demo/paymentservice:v0.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 200m
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
               apiVersion: v1
               fieldPath: status.podIP
        - name: OTEL_RESOURCE
          value: k8s.pod.ip=$(MY_POD_IP)
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          # The application SDK must use this environment variable in order to succesfully
        - name: DD_DATACENTER
          value: {{ $.Values.datacenter }}
        - name: DD_SITE
          value: datad0g.com
        - name: OTEL_AGENT_ENDPOINT
          value: "$(HOST_IP)"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(OTEL_AGENT_ENDPOINT):{{ $.Values.otlp_port }}"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=paymentservice,deployment.environment={{ $.Values.namespace }}"
        - name: PAYMENT_SERVICE_PORT
          value: "50051"

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    component: otel-demo-paymentservice
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 50051
      protocol: TCP
      name: http
  selector:
    app: paymentservice
    component: otel-demo-paymentservice
---
